matrix:
  homeserver_url: "https://matrix-client.matrix.org" #"https://matrix.tu-berlin.de" 
  user_id: "@tutor_ai:matrix.org"       #"@tutorai:matrix.tu-berlin.de" 
  access_token: "REPLACE_ME_WITH_ACCESS_TOKEN"
  refresh_token: "REPLACE_ME_WITH_REFRESH_TOKEN"
  token_endpoint: "https://account.matrix.org/oauth2/token"
  client_id: "REPLACE_ME_WITH_OAUTH_CLIENT_ID"
  token_expires_at: null
  device_id: "BOTDEVICE"
  store_path: "./store"

ollama:
  model: "gemma3:12b" #fits nicely into 16GB VRAM and is decent model
  host: "http://localhost:11434"

embeddings:
  model: "nomic-embed-text:v1.5"
  host: "http://localhost:11434"
  sparse_model: "Qdrant/bm25"

qdrant:
  url: "http://qdrant-url"
  api_key: "REPLACE_ME"
  collection: "tutor_ai_hybrid"
  prefer_grpc: false
  dense_vector_name: "dense-text-vector"
  sparse_vector_name: "sparse-text-vector"
  use_sparse: true
  top_k: 8

prompts:
  system_prompt: "Du bist TutorAI, ein hilfreicher deutschsprachiger Studienassistent für Informatikstudenten im ersten Semester.\n
    Du erhälst Fragen zu den Themen der Vorlesungen, Übungen und Tutorien. 
    Antworte knapp, präzise und freundlich. Nutze die zusätzlichen Informationen, 
    die durch das RAG bereitgestellt werden oder beantworte auf Basis deines eigenen Wissens.\n
    Kennzeichne ob die Antwort auf die Frage auf Grundlage der RAG-Informationen gegeben wird 
    oder ob du sie aus deinem eigenen Wissen beantwortest. Falls dir Informationen fehlen, sei ehrlich."

allowed_room_ids:
  - "some-random-looking-string:matrix.org"  #our test room
