version: '3'

services:
  chroma:
    image: chroma
    build:
      context: ./chroma
      dockerfile: Dockerfile
    volumes:
      - ./volumes/chroma:/chroma
      - ./volumes/index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 5001:8000
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '5002:8123'
      - '5003:9000'
    volumes:
      - ./volumes/clickhouse_data:/var/lib/clickhouse
      - ./volumes/clickhouse_logs:/var/log/clickhouse-server
      - ./volumes/backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
  
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:5000
    volumes:
      - ./webserver:/app
    depends_on:
      - mongo
      - chroma

  mongo:
    image: mongo
    restart: always
    volumes:
      - .volumes/mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5004:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
  mongo_data:
    driver: local
